--- 
- name: Debian OS Updates and base packages
  serial:
    - 100%
  hosts: 
    - all
  become: yes
  tasks:
    - name: Update Base OS
      ansible.builtin.apt:
        update_cache: yes
        upgrade: full
        autoclean: yes
    - name: Disable install recommends and suggests
      ansible.builtin.copy:
        dest: /etc/apt/apt.conf.d/80no-install-recommends
        content: |
          APT::Install-Recommends "0";
          APT::Install-Suggests "0";   

- name: Confirm sudoers.d exists
  ansible.builtin.file:
    path: /etc/sudoers.d
    state: directory
    mode: '0755'

- name: Create ansible system user
  ansible.builtin.user:
    name: ansible
    shell: /bin/bash
    system: yes
    create_home: yes
    state: present

- name: Configure ansible user to not require password for sudo
  ansible.builtin.copy:
    dest: /etc/sudoers.d/10ansible
    content: |
      # Ansible User Does Not require password
      ansible ALL=(ALL:ALL) NOPASSWD: ALL
    mode: '0644'
    force: no

# https://wiki.debian.org/Suspend
- name: Ensure /etc/systemd/sleep.conf.d directory exists
  ansible.builtin.file:
    path: /etc/systemd/sleep.conf.d
    state: directory
    mode: '0755'

# https://wiki.debian.org/Suspend
- name: Ensure /etc/systemd/logind.conf.d directory exists
  ansible.builtin.file:
    path: /etc/systemd/logind.conf.d
    state: directory
    mode: '0755'

- name: Create nosuspend.conf to disable sleep options
  ansible.builtin.copy:
    dest: /etc/systemd/sleep.conf.d/nosuspend.conf
    content: |
      [Sleep]
      AllowSuspend=no
      AllowHibernation=no
      AllowSuspendThenHibernate=no
      AllowHybridSleep=no
    mode: '0644'
    force: no

- name: Create logind.conf to prevent suspending when lid is closed
  ansible.builtin.copy:
    dest: /etc/systemd/sleep.conf.d/nosuspend.conf
    content: |
      [Login]
      HandleLidSwitch=ignore
      HandleLidSwitchDocked=ignore
    mode: '0644'
    force: no
    
- name: Install standard packages
  serial:
    - 100%
  hosts: 
    - all
  become: yes
  tasks:
    - name: Install packages
      ansible.builtin.apt:
        pkg:
          - aptitude
          - apt-transport-https
          - build-essential
          - ca-certificates
          - curl
          - debian-archive-keyring
          - debsig-verify
          - git
          - gnupg2
          - lsb-release
          - python3-pip
          - python3-setuptools
          - software-properties-common
          - vim
          - pipx
          - tmux
          - tree
        state: latest
        update_cache: true
