---
- name: Debian OS Updates and base packages
  hosts: all
  become: yes
  tasks:
    - name: Set timezone to UTC
      ansible.builtin.timezone:
        name: UTC
    - name: Set default search domain to sizza.net
      ansible.builtin.lineinfile:
        path: /etc/resolv.conf
        line: "search sizza.net"
        create: yes
        state: present
    - name: Disable install recommends and suggests
      ansible.builtin.copy:
        dest: /etc/apt/apt.conf.d/80no-install-recommends
        content: |
          APT::Install-Recommends "0";
          APT::Install-Suggests "0";
    - name: Remove standard /etc/apt/sources.list
      ansible.builtin.file:
        path: /etc/apt/sources.list
        state: absent
    - name: Create "blank" apt/sources.list
      ansible.builtin.copy:
        dest: /etc/apt/sources.list
        content: |
          # Contents moved to /etc/apt/sources.list.d/sources.list
    - name: Create apt/sources.list
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/sources.list
        content: |
          deb http://mirrors.wikimedia.org/debian/ bookworm main non-free-firmware contrib
          deb http://security.debian.org/debian-security bookworm-security main non-free-firmware contrib
          deb http://mirrors.wikimedia.org/debian/ bookworm-updates main non-free-firmware contrib
    - name: Update Base OS
      ansible.builtin.apt:
        update_cache: yes
        upgrade: full
        autoclean: yes
    - name: Add VSCODE repository key
      ansible.builtin.apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present
    - name: Add VSCODE repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
        state: present
    - name: Add Sublime repository key
      ansible.builtin.apt_key:
        url: https://download.sublimetext.com/sublimehq-pub.gpg
        state: present
    - name: Add Node repository setup script
      ansible.builtin.shell: curl -fsSL https://deb.nodesource.com/setup_current.x | bash -
    - name: Update apt cache after adding repositories
      ansible.builtin.apt:
        update_cache: yes
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - software-properties-common
          - apt-transport-https
          - curl
          - git
          - vim
          - build-essential
          - fonts-inconsolata
          - code
          - sublime-text
          - keepass2
          - ca-certificates
          - debsig-verify
          - ttf-mscorefonts-installer
          - tree
          - python3-pip
          - ansible
          - rsync
          - brightnessctl
          - alacritty
          - pipx
          - node
        state: present
    # - name: Install npm packages "eslint", "live server"
    #   ansible.builtin.shell: npm install --global live-server eslint
    - name: Set alacritty to default terminal
      ansible.builtin.shell: update-alternatives --set x-terminal-emulator /usr/bin/alacritty
    - name: Set vim to default editor
      ansible.builtin.shell: update-alternatives --set editor /usr/bin/vim
    - name: Clear and regenerate font cache
      ansible.builtin.shell: fc-cache -fv
